# Generated by Django 3.1.3 on 2021-05-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210507_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='curency',
            field=models.CharField(choices=[('iq', 'IQ'), ('$', '$')], default='IQ', max_length=50),
        ),
    ]
