# Generated by Django 3.1.3 on 2021-05-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210507_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='depatr',
            new_name='depart',
        ),
    ]
