# Generated by Django 3.2.2 on 2021-05-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20210511_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curn',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
