# Generated by Django 3.2.2 on 2021-05-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_curn_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curn',
            options={},
        ),
    ]
