# Generated by Django 3.2.2 on 2021-05-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
