# Generated by Django 3.2.2 on 2021-05-13 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_alter_repo_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repo',
        ),
    ]
