# Generated by Django 3.2.2 on 2021-05-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_delete_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
    ]
